### ISSUE TITLE
entity.save() errors on Lucee 5

### ISSUE THREAD

**Issue by elpete** [coldbox-modules/cbox-cborm#16]
See the repo for the test case: https://github.com/elpete/cborm-lucee-5-error

The quick version: on Lucee 5 `entitySave( myEntity )` works while `myEntity.save()` does not.  `myEntity.save()` works on Lucee 4 without modification.

The error:
```
Messages: lucee.runtime.orm.ORMDatasourceConnection cannot be cast to lucee.runtime.db.DatasourceConnectionImpl
```

**Comment by lmajano** [comment]
Is this an issue with us?

**Comment by elpete** [comment]
No.  It's with Lucee. :-)
